# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Breen
email: dnlbreen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 
  Website Under Construction
 
avatar: https://www.nps.gov/yose/planyourvisit/images/dr-tunnel-view-pp-bigweb_1.jpg
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danielbreen.net" # the base hostname & protocol for your site
future: true

twitter_username: dnlbreen
github_username:  dnlbreen
facebook_username: dnlbreen
linkedin_username: dnlbreen

# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"
